routes/web.php
<?php

use App\Http\Controllers\ItemController;
use App\Http\Controllers\PurchaseController;
use App\Models\Item;
use App\Models\Purchase;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard', [
        'item_count' => Item::count(),
        'purchase_count' => Purchase::count(),
    ]);
});

Route::resource('barang', ItemController::class);
Route::post('pembelian/cart/remove', [PurchaseController::class, 'removeCart'])->name('pembelian.removeCart');
Route::post('pembelian/cart/tambah', [PurchaseController::class, 'addCart'])->name('pembelian.addCart');
Route::post('pembelian/detail', [PurchaseController::class, 'detail'])->name('pembelian.detail');
Route::resource('pembelian', PurchaseController::class);

app/Models/Purchase.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Http/Controllers/PurchaseController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Purchase;
use App\Models\PurchaseDetail;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use function GuzzleHttp\Promise\all;

class PurchaseController extends Controller
{
    public function index()
    {
        if (request()->ajax()) {
            $model = Purchase::all();
            return Datatables()
                ->of($model)
                ->addIndexColumn()
                ->addColumn('date', function ($model) {
                    return Carbon::parse($model->created_at)->translatedFormat('l, d F Y H:i');
                })
                ->addColumn('total_item', function ($model) {
                    $details = PurchaseDetail::where('purchase_id', $model->id)->get();
                    $total_item = 0;
                    foreach ($details as $detail) {
                        $total_item += $detail->amount;
                    }
                    return $total_item;
                })
                ->addColumn('total_price', function ($model) {
                    return "Rp." . $model->total_price;
                })
                ->addColumn('action', function ($model) {
                    $btn = '<button type="button" id="detail" class="btn btn-info btn-sm" value="' . $model->id . '"><i class="fas fa-eye"></i></button>';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('pages.purchase.index');
    }

    public function detail(Request $request)
    {
        $details = PurchaseDetail::with('item')->where('purchase_id', $request->id)->get();
        return response()->json($details);
    }

    public function create()
    {
        $items = Item::orderBy('item_name', 'ASC')->get();
        $datas = \Cart::session('purchase')->getContent();
        $total = \Cart::session('purchase')->getSubTotal();
        return view('pages.purchase.create', compact('items', 'datas', 'total'));
    }

    public function addCart(Request $request)
    {
        $validator = Validator::make($request->only('item', 'price', 'amount'), [
            'item' => 'required',
            'amount' => 'required',
        ]);
        if ($validator->fails()) {
            return response()->json(['status' => 0, 'error' => $validator->errors()->toArray()]);
        } else {
            $item = Item::find($request->item);
            \Cart::session('purchase')->add([
                'id' => $item->id,
                'name' => $item->item_name,
                'price' => $item->unit_price,
                'quantity' => $request->amount,
            ]);
            $datas = \Cart::session('purchase')->getContent();
            $total = \Cart::session('purchase')->getSubTotal();
            return response()->json(['status' => 1, 'msg' => 'Barang Berhasil Ditambahkan ke List', 'datas' => $datas, 'total' => $total]);
        }
    }

    public function removeCart(Request $request)
    {
        \Cart::session('purchase')->remove($request->id);
        $datas = \Cart::session('purchase')->getContent();
        $total = \Cart::session('purchase')->getSubTotal();
        return response()->json(['status' => 1, 'msg' => 'Barang Berhasil Dihapus dari List', 'datas' => $datas, 'total' => $total]);
    }

    public function store(Request $request)
    {
        if (\Cart::session('purchase')->isEmpty()) {
            return back()->with('error', 'List Barang Tidak Boleh Kosong')->withInput();
        } else {
            $purchase = Purchase::create([
                'total_price' => \Cart::session('purchase')->getSubTotal()
            ]);

            foreach (\Cart::session('purchase')->getContent() as $data) {
                PurchaseDetail::create([
                    'purchase_id' => $purchase->id,
                    'item_id' => $data->id,
                    'amount' => $data->quantity,
                    'unit_price' => $data->price,
                ]);
            }
        }
        \Cart::session('purchase')->clear();
        return redirect()->route('pembelian.index')->with('success', 'Transaksi Pembelian Berhasil Disimpan');
    }
}

resources/views/pages/purchase/create.blade.php
@extends('layouts.main', ['title' => 'Transaksi Pembelian'])
@section('content')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Transaksi Pembelian</h1>
</div>
<div class="row justify-content-center">
    <div class="col-12">
        <form action="{{ route('pembelian.store') }}" method="POST">
            @csrf
            <div class="card">
                <div class="card-header">
                    <h5>Input Barang</h5>
                </div>
                <div class="card-body">
                    <div class="form-group row">
                        <label for="item" class="col-sm-3 col-form-label">Barang</label>
                        <div class="col-sm-4">
                            <select name="item" id="item" class="form-control">
                                <option value=""></option>
                                @foreach ($items as $item)
                                <option value="{{ $item->id }}">{{ $item->item_name . ' - Rp.' . $item->unit_price }}
                                </option>
                                @endforeach
                            </select>
                            <span class="text-danger error_text item_error"></span>
                        </div>
                        <label for="amount" class="col-sm-1 col-form-label">Jumlah</label>
                        <div class="col-sm-3">
                            <input type="number" class="form-control" name="amount" id="amount" min="1">
                            <span class="text-danger error_text amount_error"></span>
                        </div>
                        <div class="col-sm-1 d-flex justify-content-end">
                            <button type="button" class="btn btn-primary" id="addCart"><i
                                    class="fas fa-plus"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h5>Daftar Barang</h5>
                </div>
                @if(Session::has('error'))
                <p class="alert alert-danger text-center">{{ Session::get('error') }}</p>
                @endif
                <div class="card-body">
                    <table id="table" class="table table-bordered table-striped" style="width: 100%">
                        <thead class="text-center">
                            <tr class="bg-primary text-white">
                                <th width="5%">No</th>
                                <th>Nama Barang</th>
                                <th>Jumlah</th>
                                <th>Harga</th>
                                <th>Subtotal</th>
                                <th width="10%"><i class="fas fa-cog"></i></th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            @php $no = 1; @endphp
                            @foreach ($datas as $data)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $data->name }}</td>
                                <td>{{ $data->quantity }}</td>
                                <td>{{ $data->price }}</td>
                                <td>{{ $data->quantity * $data->price }}</td>
                                <td>
                                    <button type="button" class="btn btn-danger btn-sm" id="delCart"
                                        value="{{ $data->id }}"><i class="fas fa-times"></i></button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="row justify-content-end">
                        <div class="col-6">
                            <div class="form-group row">
                                <label for="item" class="col-sm-4 col-form-label">Total Harga</label>
                                <div class="col-sm-8">
                                    <input type="text" id="total" name="total" class="form-control" value="{{ $total }}"
                                        disabled>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary my-3">Simpan Transaksi</button>
                </div>
        </form>
    </div>
</div>
@endsection
@push('js')
<script>
    const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000
        });

    $.ajaxSetup({
        headers: {
            "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr('content')
        }
    });

    const table = $('#table').DataTable({
        searching : false,
        paging : false,
        info : false,
        responsive : true,
    });

    $(document).on('select2:open', () => {
        document.querySelector('.select2-search__field').focus();
    });

    $('#item').select2({
        theme: 'bootstrap4',
        placeholder: 'Pilih Barang',
        allowClear: true
    });

    $('#amount').on('change', function(){
        let min = parseInt($(this).attr('min'));

        if ($(this).val() < min)
        {
            $(this).val(min);
        }   
    });

    $('body').on('click', '#addCart', function() {
        let item = $('#item').val();
        let price = $('#price').val();
        let amount = $('#amount').val();
        $.ajax({
            url:'{{ route('pembelian.addCart') }}',
            method: 'POST',
            data: {
                item : item,
                price : price,
                amount : amount
            },
            dataType:'json',
            beforeSend:function(){
                $(document).find('span.error_text').text('')
            },
            success:function(result){
                if(result.status == 0){
                    $.each(result.error, function(prefix, val){
                        $('span.'+prefix+'_error').text(val[0]);
                    });
                }else{
                    Toast.fire({
                        icon: 'success',
                        title: result.msg
                    });

                    let tbody = $('#table tbody');
                    tbody.empty();

                    let no = 1;

                    $.each(result.datas, function (key, value){
                        let row = $('<tr></tr>');
                        row.append('<td>' + no++ + '</td>');
                        row.append('<td>' + value.name + '</td>');
                        row.append('<td>' + value.quantity + '</td>');
                        row.append('<td>' + value.price + '</td>');
                        row.append('<td>' + (value.quantity * value.price) + '</td>');
                        row.append('<td><button type="' + 'button"  class="' + 'btn btn-danger btn-sm" id="' + 'delCart" value="' +
                            value.id +'"><i class="' + 'fas fa-times"></i></button></td>');
                        
                        tbody.append(row);

                        $('#amount').val("");
                    })

                    $('#total').val(result.total);
                }
            }
        })
    })

    $('body').on('click', '#delCart', function() {
        var id = $(this).val();

        Swal.fire({
            title: 'Yakin Hapus Dari List ?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Ya Hapus!',
            confirmButtonColor: '#FF0000',
            cancelButtonText: 'Tidak',
            cancelButtonColor: '#3085d6',
        }).then(function(result) {
            if (result.value) {
                $.ajax({
                    type: "POST",
                    url: "{{ route('pembelian.removeCart') }}",
                    data: {
                        id:id
                    },
                    dataType: 'json',
                    success: function(result) {
                        if (result.status == 1) {
                            Toast.fire({
                                icon: 'success',
                                title: result.msg
                            });
                            let tbody = $('#table tbody');
                            tbody.empty();

                            let no = 1;

                            $.each(result.datas, function (key, value){
                                let row = $('<tr></tr>');
                                row.append('<td>' + no++ + '</td>');
                                row.append('<td>' + value.name + '</td>');
                                row.append('<td>' + value.quantity + '</td>');
                                row.append('<td>' + value.price + '</td>');
                                row.append('<td>' + (value.quantity * value.price) + '</td>');
                                row.append('<td><button type="' + 'button"  class="' + 'btn btn-danger btn-sm" id="' + 'delCart" value="' +
                                    value.id +'"><i class="' + 'fas fa-times"></i></button></td>');
                                
                                tbody.append(row);
                            });

                            $('#total').val(result.total);
                        }else{
                            Swal.fire({
                                icon: 'error',
                                title: 'Gagal...',
                                text: result.error,
                            })
                        }
                    }
                });
            }
        })
    });

</script>
@endpush

resources/views/pages/purchase/detail.blade.php
<div class="modal fade" id="modal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="title"></h4>
            </div>
            <div class="modal-body">
                <table id="tableDetail" class="table table-bordered table-striped" style="width: 100%">
                    <thead class="text-center">
                        <tr>
                            <th width="5%">No</th>
                            <th>Nama Barang</th>
                            <th>Jumlah</th>
                            <th>Harga Satuan</th>
                            <th>Subtotal</th>
                        </tr>
                    </thead>
                    <tbody class="text-center"></tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-window-close"></i>
                    Tutup</button>
            </div>
        </div>
    </div>
</div>

resources/views/pages/purchase/index.blade.php
@extends('layouts.main', ['title' => 'Rekap Transaksi Pembelian'])
@section('content')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Rekap Transaksi Pembelian</h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="table" class="table table-bordered table-striped" style="width: 100%">
                        <thead>
                            <tr>
                                <th width="5%">No.</th>
                                <th>Waktu Transaksi</th>
                                <th>Total Barang</th>
                                <th>Total Harga</th>
                                <th width="15%"><i class="fas fa-cog"></i></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@includeIf('pages.purchase.detail')
@endsection
@push('js')
<script type="text/javascript">
    const Toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000
    });
        
    $.ajaxSetup({
        headers: {
            "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr('content')
        }
    });

    @if (session('success'))
        Toast.fire({
        icon: 'success',
        title: '{!! session('success') !!}'
        });
    @endif

    const table = $('#table').DataTable({
        processing: true,
        autoWidth: false,
        serverSide: true,
        responsive: true,
        ajax: {
            url: '{{ route('pembelian.index') }}',
        },
        columns: [{
                data: 'DT_RowIndex',
                searchable: false,
                sortable: false
            },
            {
                data: 'date'
            },
            {
                data: 'total_item'
            },
            {
                data: 'total_price'
            },
            {
                data: 'action',
                searchable: false,
                sortable: false
            },
        ],
        columnDefs: [{
            className: 'text-center',
            targets: '_all'
        }]
    });

    $('body').on('click', '#detail', function() {
        let id = $(this).val();
        $.ajax({
            type: 'POST',
            url: '{{ route('pembelian.detail') }}',
            data : {id :id},
            success: function(result) {
                $('#title').html("Detail Pembelian");
                $('#modal').modal('show');

                let tbody = $('#tableDetail tbody');
                tbody.empty();

                let no = 1;

                $.each(result, function (key, value){
                    let row = $('<tr></tr>');
                    console.log(value);
                    row.append('<td>' + no++ + '</td>');
                    row.append('<td>' + value.item.item_name + '</td>');
                    row.append('<td>' + value.amount + '</td>');
                    row.append('<td>' + value.unit_price + '</td>');
                    row.append('<td>' + (value.amount * value.unit_price) + '</td>');
                    
                    tbody.append(row);
                })
            }
        });
    });
</script>
@endpush