routes/web.php
<?php

use App\Http\Controllers\ItemController;
use App\Http\Controllers\PurchaseController;
use App\Models\Item;
use App\Models\Purchase;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard', [
        'item_count' => Item::count(),
        'purchase_count' => Purchase::count(),
    ]);
});

Route::resource('barang', ItemController::class);
Route::post('pembelian/cart/remove', [PurchaseController::class, 'removeCart'])->name('pembelian.removeCart');
Route::post('pembelian/cart/tambah', [PurchaseController::class, 'addCart'])->name('pembelian.addCart');
Route::post('pembelian/detail', [PurchaseController::class, 'detail'])->name('pembelian.detail');
Route::resource('pembelian', PurchaseController::class);

resources/views/layouts/inc/ext-css.blade.php
<!-- Custom fonts for this template-->
<link href="{{ asset('template/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
<link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{{ asset('template/css/sb-admin-2.min.css') }}" rel="stylesheet">
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('template/vendor/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('template/vendor/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
<!-- SweetAlert2 -->
<link rel="stylesheet" href="{{ asset('template/vendor/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
{{-- Select2 --}}
<link href="{{ asset('template/vendor/select2/css/select2.min.css') }}" rel="stylesheet" />
<link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@x.x.x/dist/select2-bootstrap4.min.css">

resources/views/layouts/inc/ext-js.blade.php
<!-- Bootstrap core JavaScript-->
<script src="{{ asset('template/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('template/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Core plugin JavaScript-->
<script src="{{ asset('template/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

<!-- Custom scripts for all pages-->
<script src="{{ asset('template/js/sb-admin-2.min.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('template/vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('template/vendor/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('template/vendor/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('template/vendor/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<!-- SweetAlert2 -->
<script src="{{ asset('template/vendor/sweetalert2/sweetalert2.min.js') }}"></script>
{{-- Select2 --}}
<script src="{{ asset('template/vendor/select2/js/select2.min.js') }}"></script>

resources/views/layouts/inc/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Cashier App. 2022</span>
        </div>
    </div>
</footer>

resources/views/layouts/inc/navbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

</nav>

resources/views/layouts/inc/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon">
            <i class="fas fa-cash-register"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Cashier <sup>App</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item{{ (Request::segment(1) == '') ? ' active' : '' }}">
        <a class="nav-link" href="/">
            <i class="fas fa-home"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Master Data
    </div>

    <li class="nav-item{{ (Request::segment(1) == 'barang') ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('barang.index') }}">
            <i class="fas fa-box-open"></i>
            <span>Barang</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Transaksi
    </div>

    <li class="nav-item{{ (Request::segment(1) == 'pembelian' && Request::segment(2) == 'create') ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('pembelian.create') }}">
            <i class="fas fa-cart-arrow-down"></i>
            <span>Pembelian</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Rekap Transaksi
    </div>

    <li class="nav-item{{ (Request::segment(1) == 'pembelian' && Request::segment(2) == '') ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('pembelian.index') }}">
            <i class="fas fa-list"></i>
            <span>Pembelian</span></a>
    </li>

</ul>