routes/web.php
<?php

use App\Http\Controllers\ItemController;
use App\Http\Controllers\PurchaseController;
use App\Models\Item;
use App\Models\Purchase;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard', [
        'item_count' => Item::count(),
        'purchase_count' => Purchase::count(),
    ]);
});

Route::resource('barang', ItemController::class);
Route::post('pembelian/cart/remove', [PurchaseController::class, 'removeCart'])->name('pembelian.removeCart');
Route::post('pembelian/cart/tambah', [PurchaseController::class, 'addCart'])->name('pembelian.addCart');
Route::post('pembelian/detail', [PurchaseController::class, 'detail'])->name('pembelian.detail');
Route::resource('pembelian', PurchaseController::class);

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class ItemController extends Controller
{
    public function index()
    {
        if (request()->ajax()) {
            $model = Item::all();
            return Datatables()
                ->of($model)
                ->addIndexColumn()
                ->addColumn('unit_price', function ($model) {
                    return "Rp." . $model->unit_price;
                })
                ->addColumn('action', function ($model) {
                    $btn = '<button type="button" id="edit" class="btn btn-warning btn-sm" value="' . $model->id . '"><i class="fas fa-edit"></i></button>';
                    $btn = $btn . '<button type="button" id="delete" class="btn btn-danger btn-sm" value="' . $model->id . '"><i class="fas fa-trash-alt"></i></button>';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('pages.item.index');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'item_name' => ['required', Rule::unique('items', 'item_name')->ignore($request->id, 'id')],
            'unit_price' => 'required'
        ]);
        if ($validator->fails()) {
            return response()->json(['status' => 0, 'error' => $validator->errors()->toArray()]);
        } else {
            $query =  Item::updateOrCreate(
                [
                    'id' => $request->id
                ],
                [
                    'item_name' => $request->item_name,
                    'unit_price' => $request->unit_price,
                ]
            );
            if ($query) {
                return response()->json(['status' => 1, 'msg' => 'Data Berhasil Disimpan']);
            }
        }
    }

    public function edit($id)
    {
        $item = Item::find($id);
        return response()->json($item);
    }

    public function destroy($id)
    {
        Item::find($id)->delete();
        return response()->json(['success' => 'Data Berhasil Dihapus']);
    }
}

resources/views/pages/item/index.blade.php
@extends('layouts.main', ['title' => 'Data Barang'])
@section('content')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Data Barang</h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <button type="button" id="add" class="btn btn-primary"><i class="fas fa-plus-circle"></i>
                    Tambah</button>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="table" class="table table-bordered table-striped" style="width: 100%">
                        <thead>
                            <tr>
                                <th width="5%">No.</th>
                                <th>Nama Barang</th>
                                <th>Harga Satuan</th>
                                <th width="15%"><i class="fas fa-cog"></i></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@includeIf('pages.item.modal')
@endsection
@push('js')
<script type="text/javascript">
    const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000
        });
        
        $.ajaxSetup({
            headers: {
                "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr('content')
            }
        });
        const table = $('#table').DataTable({
            processing: true,
            autoWidth: false,
            serverSide: true,
            responsive: true,
            ajax: {
                url: '{{ route('barang.index') }}',
            },
            columns: [{
                    data: 'DT_RowIndex',
                    searchable: false,
                    sortable: false
                },
                {
                    data: 'item_name'
                },
                {
                    data: 'unit_price'
                },
                {
                    data: 'action',
                    searchable: false,
                    sortable: false
                },
            ],
            columnDefs: [{
                className: 'text-center',
                targets: '_all'
            }]
        });

        $('#add').click(function() {
            $('#main_form')[0].reset();  
            $('#id').val('');  
            $('span.error_text').html("");
            $('#title').html("Tambah Barang");
            $('#modal').modal('show');
        });

        $('body').on('click', '#edit', function() {
            let id = $(this).val();
            $('span.error_text').html("");
            $.ajax({
                type: "GET",
                url: "/barang/" + id + '/edit',
                success: function(response) {
                    $('#title').html("Ubah Barang");
                    $('#modal').modal('show');
                    $('#id').val(response.id);
                    $('#item_name').val(response.item_name);
                    $('#unit_price').val(response.unit_price);
                }
            });
        });

        $('body').on('click', '#delete', function() {
            let id = $(this).val();

            Swal.fire({
                title: 'Yakin Hapus ?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Ya Hapus!',
                confirmButtonColor: '#FF0000',
                cancelButtonText: 'Tidak',
                cancelButtonColor: '#3085d6',
            }).then(function(result) {
                if (result.value) {
                    $.ajax({
                        type: "DELETE",
                        url: "/barang/" + id,
                        success: function(response) {
                            if (response.success) {
                                Toast.fire({
                                    icon: 'success',
                                    title: response.success
                                });
                                table.ajax.reload();
                            }
                            if (response.error) {
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Gagal...',
                                    text: response.error,
                                })
                            }
                        }
                    });
                }
            })
        });

        $('#main_form').on('submit', function(e){
            e.preventDefault();

            $.ajax({
                url:$(this).attr('action'),
                method:$(this).attr('method'),
                data:new FormData(this),
                processData:false,
                dataType:'json',
                contentType:false,
                beforeSend:function(){
                    $(document).find('span.error_text').text('')
                },
                success:function(data){
                    if(data.status == 0){
                        console.log(data.error);
                        $.each(data.error, function(prefix, val){
                            $('span.'+prefix+'_error').text(val[0]);
                        });
                    }else{
                        $('#main_form')[0].reset();
                        $('#modal').modal('hide');
                        table.ajax.reload();
                        Toast.fire({
                            icon: 'success',
                            title: data.msg
                        });
                    }
                }
            })
        })
</script>
@endpush

resources/views/pages/item/modal.blade.php
<div class="modal fade" id="modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="title"></h4>
            </div>
            <div class="modal-body">
                <form action="{{ route('barang.store') }}" id="main_form" class="form-horizontal" method="POST">
                    <input type="hidden" name="id" id="id">
                    <div class="form-group">
                        <label for="item_name" class="col-sm-6">Nama Barang</label>
                        <div class="col-sm-12">
                            <input type="text" name="item_name" id="item_name" class="form-control">
                            <span class="text-danger error_text item_name_error"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="unit_price" class="col-sm-6">Harga</label>
                        <div class="col-sm-12">
                            <input type="number" name="unit_price" id="unit_price" class="form-control" step="any">
                            <span class="text-danger error_text unit_price_error"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i>
                            Simpan</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal"><i
                                class="fas fa-window-close"></i>
                            Batal</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>